name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Configure Awscli
        run: |
          make awscli
        env:
          _AWS_ACCESS_KEY_ID: ${{ secrets._AWS_ACCESS_KEY_ID }}
          _AWS_SECRET_ACCESS_KEY: ${{ secrets._AWS_SECRET_ACCESS_KEY }}

      - name: Install npm dependecy 
        run: make Install

      - name: Install quasar CLI
        run: make quasar

      - name: Build quasar
        run: make build

      - name: Deployment on S3
        run: make deploy
