<template>
  <q-page class="">
    <div class="help-center">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="fixed-left">
              <ul class="sidebar-nav">
                  <!-- <li class="nav-item active">
                    <button @click="goto('community_guidelines')">Community Guidelines</button>
                  </li>
                  <li class="nav-item">
                    <button @click="goto('privacy_policy')">Privacy Policy</button>
                  </li>
                  <li class="nav-item">
                    <button @click="goto('terms&condition')">Terms & Condition</button>
                  </li>
                  <li class="nav-item">
                      <button @click="goto('event_policy')">Event Policy </button>
                  </li>
                  <li class="nav-item">
                    <button @click="goto('cookies_policy')">Cookies Policy </button>
                </li> -->
                <li><router-link :to="{ name: 'community-guideline' }">Community Guidelines</router-link></li>
                <li><router-link :to="{ name: 'pricacy' }">Privacy Policy</router-link></li>
                <li class="active"><router-link :to="{ name: 'terms-and-condition' }">Terms & Condition</router-link></li>
                <li><router-link :to="{ name: 'event-policy' }">Event Policy</router-link></li>
                <li><router-link :to="{ name: 'cookies-policy' }">Cookies Policy</router-link></li>

              </ul>
            </div>
          </div>
          <div class="col-md-9 right-content">
            <section class="" id="three" ref="terms&condition">
              <div class="pt-5">
                <h2 class="h1 mb-4">Terms & Condition</h2>
                <p><b>Here you will find Foodism's Terms and Conditions. Please, read carefully. If you have any questions, don't hesitate to contact us.</b></p>
                <div class="mb-5">
                  <p>This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Service for access or usage of the Application and the Servianyoneces.</p>
                </div>
                <div class="mb-5">
                  <h6>Please read these terms of service carefully as they contain important information regarding your legal rights, remedies and obligations. These include various limitations and exclusions.</h6>
                  <p>Foodism.xyz Private Limited, proprietor and owner of “Foodism” (hereafter referred to as ”Foodism”, "we", "us", or "our" and includes group companies, intermediaries, subsidiary companies and affiliates) provides an online platform that connects food enthusiasts and creates creative and engaging content related to food, health, wellness, lifestyle and about the evolving food practices through a diverse mix of articles, blogs, listicles, videos (collectively, the “Services”), which Services are accessible at https://foodism.xyz/ and any other websites/applications through which Foodism makes the Services available (collectively, the “Site”). All references herein to “User”, “your” or “you” refer to any person participating as a user of the Site.</p>
                  <p>By using the Site, you agree to comply with and be legally bound by the terms and conditions of these Terms of Service ("Terms"), whether or not you become a registered user of the Services. These Terms govern your access to and use of the Site and Services and constitute a binding legal agreement between you and Foodism. Please read these Terms and our Privacy Policy carefully. Failure to use the Site in accordance with these Terms may subject you to civil and criminal penalties.</p>
                  <p>These terms may be subject to change from time to time, and accordingly, you are advised to refer back to these terms from time to time. By continuing to access or use the site or services after we have posted a modification on the site or have provided you with notice of a modification, you are indicating that you agree to be bound by the modified terms. If the modified terms are not acceptable to you, your only recourse is to cease using the site and services.</p>
                </div>

                <div class="mb-5">
                  <h3>Eligibility</h3>
                  <div class="">
                    <p>The site and services are intended solely for persons aged 18 or older. By accessing or using the site or services you represent and warrant that you are 18 or older. We reserve the right to request proof of age at any stage so that we can verify that minors under the age of 18 are not using the Website. In the event that it comes to our knowledge that a person under the age of 18 is using the site, we will prohibit and block such members from accessing the site and will make all efforts to promptly delete any Personal Information (as defined in our Privacy Policy) with regard to such members. Foodism will not be liable for any loss or damage arising from the unauthorised access to or use of your site or services. Upon termination for any reason, Foodism will disable and/or delete your Account at its own discretion.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>No Endorsement</h3>
                  <div class="">
                    <p>Foodism does not endorse any content or any other information listed from time to time. Furthermore, our terms of service may require every user to register and provide actual and accurate information, however, we do not attempt to confirm and do not confirm any user/member’s purported identity. Before your interaction as a user or your usage of the website and the services, you will be responsible for determining the identity and suitability of others who you contact via the website and services.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Content Posted by Users</h3>
                  <div class="">
                    <p>We may even provide a social-media forum and other interaction platform options; however, we will never be responsible for the identity of the user who you choose to interact with. In no way will we be responsible for any damage or harm of any nature, resulting from your interaction/s with other users/members. By using the website and services, you agree that any legal remedy or liability that you seek to obtain for actions or omissions of other users will be limited to a claim against the particular users/members and you agree not to impose any liability on or seek legal remedy from Foodism with respect to such actions or omissions.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Errors and Omissions</h3>
                  <div class="">
                    <p>Occasionally there may be information on the Foodism website or application that contains typographical errors, inaccuracies or omissions that may relate to services provided on the platforms. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information related to the website or application that is inaccurate at any time without prior notice. We undertake no obligation to update, amend or clarify information in the Service or on any related platforms, except as required by law. No specified update or refresh date applied in the Service or on any related platform should be taken to indicate that all information in the Service or on the website/application has been modified or updated.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Contest Policy</h3>
                  <div class="">
                    <p>Users agree that all the recipes submitted on Foodism during the contest period need to be the exclusive property of Foodism or foodism.xyz. Users further understand that each recipe or any other related content submitted for uploading on Foodism’s platforms is cross-verified on other platforms in order to avoid plagiarism. If a recipe or any other content is found plagiarised, Foodism reserves the right to reject the same and not upload it on the platform.</p>
                    <p>In case a user who wants to participate in the contest wishes to upload the recipe on their social media platforms, they can do so after submitting it on Foodism.xyz and once it is approved on the website, users may also tag Foodism.</p>
                    <p>In case Foodism discovers that the recipe is posted on any other platform before submitting to the Foodism platforms, Foodism will not consider the recipe for the current contest.</p>
                    <p>We encourage our users and participants to post organic and authentic content in order to maintain the community guidelines of Foodism.xyz.</p>
                    <b class="px-3">View Counts</b>
                    <ul>
                      <li>All views are counted till midnight on the last day of the contest. The number presented by Foodism.xyz will be final.</li>
                      <li>Views on organic content will only be counted</li>
                      <li>Foodism reserves all rights to the view count information</li>
                    </ul>

                    <b class="px-3">Prize Money </b>
                    <ul>
                      <li>It will take 7-14 working days for the Prize Money to be deposited into the winner's account beginning from the day the accounting department receives the payment details.</li>
                      <li>Foodism has the right to restrict payment to participants in case of plagiarised or non-exclusive content.</li>
                      <li>Payment can be done in parts or as a whole at the discretion of Foodism.xyz</li>
                      <li>Payment will be credited to the informed bank account of the user</li>
                    </ul>

                    <b class="px-3">Recipe Approval Guidelines</b>
                    <ul>
                      <li>All the details must be filled correctly.</li>
                      <li>The Thumbnail of the video/written recipe needs to be of good quality, non-blurred, related to the recipe, and non-stock real image.</li>
                      <li>Ingredients and Method shall be filled correctly</li>
                      <li>Categories and Subcategories selected must be relevant</li>
                      <li>The selection of Tags needs to be checked.</li>
                      <li>In the case of Video recipes, the recipe links are not valid for any contests, and links other than YouTube are not supported on our platform.</li>
                      <li>In case of any description or Tips mentioned in the recipe, it needs to be checked whether it is relevant or not.</li>
                      <li>In case a recipe is submitted for a particular contest, then the authenticity of its exclusivity will be checked.</li>
                      <li>In case of user submitting recipes in form of any collaborations, it won't be considered as valid entry for any events/contests by foodism.</li>
                      <li>Approvals are done on a daily basis</li>
                    </ul>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>User Conduct</h3>
                  <div class="">
                    <p>Your use of the Website is subject to all applicable laws and regulations, and you are solely responsible for the substance of your communications through the website/application and availing of services. By posting information in or otherwise using any communications service, chat room, message board, newsgroup, or other interactive services that may be available to you on or through our website/application, you agree that you will not upload, share, post, or otherwise distribute or facilitate distribution of any content - including text, communications, software, images, sounds, data, or other information - that:</p>
                    <ol>
                      <li>Is unlawful, threatening, abusive, harassing, defamatory, libellous, deceptive, fraudulent, invasive of another's privacy, tortuous, contains explicit or graphic descriptions or accounts of sexual acts (including but not limited to sexual language of a violent or threatening nature directed at another individual or group of individuals), or otherwise violates our rules or policies;</li>
                      <li>Victimizes, harasses, degrades, or intimidates an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability;</li>
                      <li>Infringes on any patent, trademark, trade secret, copyright, right of publicity, or other proprietary rights of any party;</li>
                      <li>Constitutes unauthorized or unsolicited advertising, junk or bulk email (also known as "spamming"), chain letters, any other form of unauthorized solicitation, or any form of lottery or gambling;</li>
                      <li>Contains software viruses or any other computer code, files, or programs that are designed or intended to disrupt, damage, or limit the functioning of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any data or other information of any third party;</li>
                      <li>Impersonates any person or entity, including any of our employees or representatives.</li>
                    </ol>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Third-Party Links</h3>
                  <div class="">
                    <p>The Site and Services may contain links to third-party websites or resources. You acknowledge and agree that Foodism is not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by Foodism of such websites or resources or the content, products, or services available from such websites or resources. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources or the content, products or services on or available from such websites or resources.</p>
                    <p>Some commercials, advertisements and/or sponsored links, whether within or beside the Website may be integrated. By clicking the advertisements you may be transferred to a website of an advertiser or receive any other messages, information or offers from the advertiser and from others. All the information contained in such commercials and advertisements belongs solely to the advertisers and Foodism makes no warranties or representations as to such advertisements, whether or not Foodism has control over such advertisements. Foodism, advertisers and/or third parties related thereto may be entitled to certain shares of the earnings for such commercials. You agree, acknowledge and consent that no right, title or interest is or shall be granted to you in any way with respect to any revenue share whatsoever in relation thereto.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Intellectual Property Rights</h3>
                  <div class="">
                    <p>The Site, Services and content are protected by copyright, trademark, and other laws. You acknowledge and agree that the Site, Services and content, including all associated intellectual property rights, are the exclusive property of Foodism and its licensors. You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Site, Services or Collective Content. All trademarks, service marks, logos, trade names, and any other proprietary designations of Foodism used on or in connection with the Site, Services, and content may be trademarks or registered trademarks of Foodism or other parties. Trademarks, service marks, logos, trade names and any other proprietary designations of third parties used on or in connection with the Site, Services, and content are used for identification purposes only and may be the property of their respective owners. As a Chef, Guest or Member, you understand and agree that you are bound by the additional Terms, Guidelines and Policies that apply to your use of the Site, Services and content, related to Trademark & Branding Guidelines.</p>
                    <b>Indemnity</b>
                    <p>You agree to indemnify and hold harmless, without objection, Foodism, its officers, directors, employees and agents from and against any claims, actions and/or demands and/or liabilities and/or losses and/or damages whatsoever arising from or resulting from your use of the site and services or breach of the terms; arising out of or in any way connected with your access to or use of the Site, Services, content or your violation of these Terms; your content; your interaction with any other user, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Liability</h3>
                  <div class="">
                    <p>You acknowledge and agree that neither Foodism nor its affiliates, directors, employees, agents, contractors, service providers or any other party involved in creating, producing, the site, services, and/or it’s related content will be liable for any incidental, special, exemplary or consequential damages, including lost profits, loss of data or loss of goodwill, service interruption, computer damage or system failure or the cost of substitute products or services or for any damages for personal or bodily injury or emotional distress arising out of or in connection with these terms, from the use of or inability to use the site, services, and/or it’s related content, from any communications, interactions or meetings with other users of the site or services or other persons with whom you communicate or interact as a result of your use of the site or services whether based on warranty, contract, tort (including negligence), product liability or any other legal theory and whether or not Foodism has been informed of the possibility of such damage.</p>
                    <p>In sum, in no event shall Foodism’s total liability to you for all damages or/and losses or/and causes of action exceed the amount paid by you to Foodism, if any, that is related to the cause of action.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Disclaimer</h3>
                  <div class="">
                    <p>You use the website or concerned application at your sole risk. We provide these platforms "As is" and "As available". We expressly disclaim to the full extent permitted by law all warranties of any kind related to the website or the application & the content obtained through these platforms, whether express or implied, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. You will be solely responsible for any damage to your computer system or loss of data that results from your use of the website or our application.</p>
                    <p>We make no warranty that (1) these platforms will meet your requirements; (2) the platforms will be uninterrupted, timely, secure, or error-free; (3) the website/application results will be accurate or reliable; (4) the quality of any content obtained by you through these platforms will meet your expectations; or (5) the platforms, our servers, or communications sent from us will be free of viruses or other harmful components.]</p>
                    <p>No information obtained by you from us or through the website will create any warranty not expressly stated in these terms.</p>
                    <p>You further acknowledge and agree that Foodism does not conduct background checks on any users, including, but not limited to, service providers, cooks or members. The application, services, collective content and referral program are provided "As is", without warranty of any kind, either express or implied.</p>
                    <p>Foodism makes no warranty regarding the services or collective content or the accuracy, timeliness, truthfulness, completeness or reliability of any collective content obtained through the application, services or referral program. No advice or information, whether oral or written, obtained from Foodism or through the website, services or collective content, will create any warranty not expressly made herein.</p>
                    <p>You are solely responsible for all of your communications and interactions with other users of the website or services and with other persons with whom you communicate or interact as a result of your use of the website or services, including, but not limited to, any users. You understand that Foodism does not make any attempt to verify the statements of users of the website or services.</p>
                    <p>You agree to take reasonable precautions in all communications and interactions with other users of the website or services and with other persons with whom you communicate or interact as a result of your use of the website or services, including, but not limited to, users, particularly if you decide to meet offline or in person and agree that Foodism will never be liable for any such interactions or meetings.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Feedback</h3>
                  <div class="">
                    <p>We welcome and encourage you to provide feedback, comments and suggestions for improvements to the Site and Services ("Feedback"). You may submit Feedback by emailing us at <a href="mailto:help@foodism.xyz">help@foodism.xyz</a> or through the "Contact" section of the website. You acknowledge and agree that all feedback will be the sole and exclusive property of Foodism and you hereby irrevocably assign to Foodism and agree to irrevocably assign to Foodism all of your right, title, and interest in and to all Feedback, including without limitation all worldwide patent, copyright, trade secret, moral and other proprietary or intellectual property rights therein.</p>
                    <p>If you come across any User who you feel is acting or has acted inappropriately, including but not limited to any one who (i) engages in offensive, violent or inappropriate behaviour, (ii) you suspect of stealing from you, or (iii) engages in any other disturbing conduct, you should immediately report such person to Foodism at <a href="mailto:help@foodism.xyz">help@foodism.xyz</a>.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Entire Agreement</h3>
                  <div class="">
                    <p>The terms of service, conditions, policies and any document expressly referred to in them constitute the whole agreement between us and supersede all previous discussions, correspondence, negotiations, previous arrangement, understanding or agreement between us relating to the subject matter of any contract.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Termination</h3>
                  <div class="">
                    <p>We may terminate or suspend access to our website/application and/or our services immediately, without prior notice or liability, for any reason whatsoever, including without limitation if we observe any breach of our terms of service, policies etc.</p>
                    <p>Upon termination, your right to use the services will immediately cease. If you wish to terminate your account, you may simply discontinue using the services. All the provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, disclaimers, indemnity and limitations of liability.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Force Majeure</h3>
                  <div class="">
                    <p>We will not be liable or responsible for any failure to perform or delay in performance of, any of our obligations under a Contract that is caused by events outside our reasonable control which will be considered as a Force Majeure event. A Force Majeure Event includes any act, event, non-happening, omission or accident beyond our reasonable control and includes in particular, without limitation, strikes, lock-outs or other industrial action, civil commotion, riot, invasion, terrorist attack or threat of terrorist attack, war (whether declared or not) or threat or preparation for war; fire, explosion, storm, flood, earthquake, subsidence, epidemic or other natural disasters; the impossibility of the use of railways, shipping, aircraft, motor transport or other means of public or private transport; the impossibility of the use of public or private telecommunications networks and the acts, decrees, legislation, regulations or restrictions of any government.</p>
                    <p>Our performance under any Contract is deemed to be suspended for the period that the Force Majeure event/s continues and we will have an extension of time for performance for the duration of that period. We will use our reasonable endeavours to bring the Force Majeure event to a close or to find a solution by which our obligations under the contract may be performed despite the Force Majeure event.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Waiver & Severability</h3>
                  <div class="">
                    <p>The failure of Foodism to enforce any right or provision of these Terms will not constitute a waiver of future enforcement of that right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Foodism. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise. If for any reason an arbitrator or a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Dispute Resolution, Governing Law & Jurisdiction</h3>
                  <div class="">
                    <p>These Terms of Service are governed by the laws of India. The courts in Ahmedabad, India shall have exclusive jurisdiction over any claim or matter arising out of these Terms of Service. Unless you have entered into an additional agreement with Foodism that provides for an alternative dispute resolution mechanism, you agree that any dispute arising between you and Foodism which cannot be resolved amicably or by mediation shall be conclusively resolved by a sole Arbitrator appointed by Foodism. The Arbitration shall be conducted as per the Arbitration rules laid down under the Arbitration and Conciliation Act, 1996, and any modification/amendment effected thereafter from time to time. The arbitration shall be conducted in the English language and the award passed by the Arbitrator shall be final and binding on both parties. The cost of arbitration shall be borne by you.</p>
                    <p>These Terms of Service will be interpreted in accordance with the laws of India. You and we agree to submit to the personal jurisdiction of the court of Ahmedabad for any claim or matter arising out of these Terms of Service.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Changes To Terms Of Service</h3>
                  <div class="">
                    <p>You can review the most current version of the Terms of Service at any time on this page. We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes on to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.</p>
                  </div>
                </div>
                <div class="mb-5">
                  <h3>Contact Us</h3>
                  <div class="">
                    <p>Please contact us for any questions or comments, including all inquiries related to services and usage regarding this Site.</p>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>

  </q-page>
</template>

<script>
import { defineComponent } from 'vue';
import { ref } from 'vue'

export default defineComponent({
  name: 'TermsCondition',
  setup () {
    return {
    }
  },
  methods: {
    goto(refName) {
    	var element = this.$refs[refName];
      console.log(element);
      var top = element.offsetTop;

      window.scrollTo(0, top);
    }
  }
})
</script>
