# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
          - 14.17.0
          - 16.X
          - 17.x
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing quasar-cli
      run: npm i -g @quasar/cli
    - name: Installing Dependency
      run: npm ci
    - name: Building quasar
      run: quasar build
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: 
          - 14.17.0
          - 16.X
          - 17.x
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing quasar-cli
      run: npm i -g @quasar/cli
    - name: Installing Dependency
      run: npm ci
    - name: Building quasar
      run: quasar build
